site_name: Conflux Wiki
site_description: Conflux Wiki
site_author: Conflux Wiki Team
site_url: https://conflux-wiki.github.io/
repo_name: conflux-wiki/conflux-wiki
repo_url: https://github.com/conflux-wiki/conflux-wiki/
edit_uri: blob/master/docs/zh/docs/
copyright: Copyright &copy; 2020 - 2021 Conflux Wiki Team
theme:
  name: material
  #name: mkdocs
  language: zh
  palette:
    primary: white
    accent: red
    scheme: preference
  icon:
    repo: fontawesome/brands/github-alt
  logo: static/img/logo.png
  features:
  - navigation.tabs
  - navigation.tabs.sticky
  - search.suggest
  - search.highlight
  - search.share
  font:
    text: Noto Sans
    code: Source Code Pro
plugins:
- search
#- minify:
#    minify_html: true
nav:
- Start:
  - index.md
  - usage.md
  - 贡献指南:
    - contribute/before-contributing.md
    - contribute/basic-contribute-approach.md
    - contribute/documentation-requirement.md
    - contribute/translation.md
  - discussion.md
- Introduction:
  - introduction/history.md
  - introduction/link.md
  - introduction/highlight-time.md
- Crypto:
  - crypto/introduction.md
  - 基础数学知识:
    - crypto/basic/introduction.md
  - 古典密码:
    - crypto/classical/introduction.md
    - crypto/classical/monoalphabetic.md
    - crypto/classical/polyalphabetic.md
    - crypto/classical/others.md
    - crypto/classical/summary.md
  - 流密码:
    - crypto/streamcipher/intro.md
    - 伪随机数生成器:
      - crypto/streamcipher/prng/intro.md
      - crypto/streamcipher/prng/csprng.md
      - crypto/streamcipher/prng/problem.md
    - 线性同余生成器:
      - crypto/streamcipher/lcg/intro.md
      - crypto/streamcipher/lcg/challenge.md
    - 反馈移位寄存器:
      - crypto/streamcipher/fsr/intro.md
      - crypto/streamcipher/fsr/lfsr.md
      - crypto/streamcipher/fsr/nfsr.md
    - 特殊流密码:
      - crypto/streamcipher/special/rc4.md
  - 块加密:
    - crypto/blockcipher/introduction.md
    - ARX:
      - crypto/blockcipher/arx-operations.md
    - DES:
      - crypto/blockcipher/des.md
    - IDEA:
      - crypto/blockcipher/idea.md
    - AES:
      - crypto/blockcipher/aes.md
    - Simon and Speck:
      - crypto/blockcipher/simon-speck.md
    - 分组模式:
      - crypto/blockcipher/mode/introduction.md
      - crypto/blockcipher/mode/padding.md
      - crypto/blockcipher/mode/ecb.md
      - crypto/blockcipher/mode/cbc.md
      - crypto/blockcipher/mode/pcbc.md
      - crypto/blockcipher/mode/cfb.md
      - crypto/blockcipher/mode/ofb.md
      - crypto/blockcipher/mode/ctr.md
      - crypto/blockcipher/mode/padding-oracle-attack.md
  - 非对称加密:
    - crypto/asymmetric/introduction.md
    - RSA:
      - crypto/asymmetric/rsa/rsa_theory.md
      - crypto/asymmetric/rsa/rsa_module_attack.md
      - crypto/asymmetric/rsa/rsa_e_attack.md
      - crypto/asymmetric/rsa/rsa_d_attack.md
      - crypto/asymmetric/rsa/rsa_coppersmith_attack.md
      - crypto/asymmetric/rsa/rsa_chosen_plain_cipher.md
      - crypto/asymmetric/rsa/rsa_side_channel.md
      - crypto/asymmetric/rsa/rsa_pkcs_attack.md
      - crypto/asymmetric/rsa/rsa_complex.md
    - 背包加密:
      - crypto/asymmetric/knapsack/knapsack.md
    - 离散对数相关:
      - crypto/asymmetric/discrete-log/discrete-log.md
      - crypto/asymmetric/discrete-log/elgamal.md
      - crypto/asymmetric/discrete-log/ecc.md
    - 格密码:
      - crypto/asymmetric/lattice/overview.md
      - crypto/asymmetric/lattice/introduction.md
      - crypto/asymmetric/lattice/lattice-reduction.md
      - crypto/asymmetric/lattice/cvp.md
  - 哈希函数:
    - crypto/hash/introduction.md
    - MD5:
      - crypto/hash/md5.md
    - SHA1:
      - crypto/hash/sha1.md
    - FNV:
      - crypto/hash/fnv.md
    - Hash Attack:
      - crypto/hash/attack.md
    - crypto/hash/complex.md
  - 数字签名:
    - crypto/signature/introduction.md
    - RSA 数字签名:
      - crypto/signature/rsa.md
    - ElGamal 数字签名:
      - crypto/signature/elgamal.md
    - DSA 数字签名:
      - crypto/signature/dsa.md
  - 攻击思想总结:
    - crypto/attack-summary/attack-mode.md
    - 中间相遇攻击:
      - crypto/attack-summary/meet-in-the-middle.md
    - 比特攻击:
      - crypto/attack-summary/bit-attack.md
  - 证书格式:
    - crypto/certificate/introduction.md
- Development:
  - development/introduction.md
  - 生态开发激励:
    - development/incentive-guide.md
  - 开发工具及相关资源介绍:
    - development/tools.md
    - development/resources.md
  - ConfluxScan教程:
    - development/apply-contract-fee.md
    - development/address-NFT.md
    - development/register-contract-and-token-display.md
    - development/get-lp-token-address.md
    - development/internal-transaction.md
    - development/address-convertor.md
  - Portal钱包教程:
    - development/portal.md
    - development/portal-setting.md
    - development/add-token-to-portal.md
    - development/portal-faucet.md
    - development/portal-drip.md
    - development/mobile-portal.md
- Ecosystem:
  - ecosystem/introduction.md
  - Conflux基础生态教程:
    - ecosystem/wcfx-cfx-exchange.md
    - ecosystem/governance.md
  - 常见生态介绍及教程:
    - ecosystem/tspace.md
    - ecosystem/nft-box.md
    - ecosystem/shuttleflow.md
    - ecosystem/moonswap.md
    - ecosystem/phantom.md
    - ecosystem/dan.md
    - ecosystem/guguo.md
    - ecosystem/bountyv2.md
    - ecosystem/triangledao.md
    - ecosystem/stampers.md
- Web:
  - web/introduction.md
  - SQL 注入:
    - web/sqli.md
  - XSS 跨站脚本攻击:
    - web/xss.md
  - CSRF 跨站请求伪造:
    - web/csrf.md
  - SSRF 服务端请求伪造:
    - web/ssrf.md
  - PHP 代码审计:
    - web/php/php.md
- BlockChain:
  - blockchain/introduction.md
  - Ethereum Security:
    - blockchain/ethereum/introduction.md
    - blockchain/ethereum/basics.md
    - blockchain/ethereum/selector-encoding.md
    - blockchain/ethereum/storage.md
    - blockchain/ethereum/opcodes.md
    - Known Attacks:
      - blockchain/ethereum/attacks/introduction.md
      - blockchain/ethereum/attacks/re-entrancy.md
      - blockchain/ethereum/attacks/overflow-underflow.md
      - blockchain/ethereum/attacks/randomness.md
      - blockchain/ethereum/attacks/airdrop-hunting.md
      - blockchain/ethereum/attacks/shortaddress.md
      - blockchain/ethereum/attacks/delegatecall.md
      - blockchain/ethereum/attacks/uninitialized-storage-pointer.md
      - blockchain/ethereum/attacks/arbitrarywrite.md
      - blockchain/ethereum/attacks/create2.md
      - blockchain/ethereum/attacks/jump-oriented-programming.md
    - blockchain/ethereum/reverse.md
    - blockchain/ethereum/challenges.md
    - blockchain/ethereum/resources.md
  - Public Blockchain Security:
    - blockchain/publicblockchain/introduction.md
    - blockchain/publicblockchain/approve.md
- NFT:
  - nft/introduction.md
- DAO:
  - dao/introduction.md
markdown_extensions:
- admonition
- md_in_html
- codehilite:
    guess_lang: false
- def_list
- footnotes
- meta
- toc:
    permalink: true
- pymdownx.arithmatex
- pymdownx.caret
- pymdownx.critic
- pymdownx.details
- pymdownx.emoji:
    emoji_index: !!python/name:materialx.emoji.twemoji ''
    emoji_generator: !!python/name:materialx.emoji.to_svg ''
- pymdownx.highlight
- pymdownx.inlinehilite
- pymdownx.keys
- pymdownx.magiclink
- pymdownx.mark
- pymdownx.smartsymbols
- pymdownx.superfences:
    custom_fences:
    - name: mermaid
      class: mermaid
      format: !!python/name:pymdownx.superfences.fence_code_format ''
- pymdownx.tasklist:
    custom_checkbox: true
- pymdownx.tilde
extra:
  alternate:
  - link: /
    name: zh - 汉语
  - link: /en/
    name: en - English
  copyright: CC BY-NC-SA 4.0
extra_javascript:
- https://cdnjs.loli.net/ajax/libs/pangu/3.3.0/pangu.min.js
- static/js/extra.js
- https://cdnjs.loli.net/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-MML-AM_CHTML
extra_css:
- static/css/extra.css
